# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_settings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogSettings(object):
    def setupUi(self, DialogSettings):
        DialogSettings.setObjectName(_fromUtf8("DialogSettings"))
        DialogSettings.setWindowModality(QtCore.Qt.WindowModal)
        DialogSettings.resize(331, 447)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogSettings.sizePolicy().hasHeightForWidth())
        DialogSettings.setSizePolicy(sizePolicy)
        DialogSettings.setMinimumSize(QtCore.QSize(331, 447))
        DialogSettings.setMaximumSize(QtCore.QSize(335, 447))
        DialogSettings.setModal(False)
        self.gridLayoutWidget = QtGui.QGridLayout(DialogSettings)
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.buttonBox = QtGui.QDialogButtonBox(DialogSettings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayoutWidget.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.boxSearchSettings = QtGui.QGroupBox(DialogSettings)
        self.boxSearchSettings.setMaximumSize(QtCore.QSize(450, 800))
        self.boxSearchSettings.setObjectName(_fromUtf8("boxSearchSettings"))
        self.gridLayoutWidgetSettings = QtGui.QGridLayout(self.boxSearchSettings)
        self.gridLayoutWidgetSettings.setObjectName(_fromUtf8("gridLayoutWidgetSettings"))
        self.verticalLayoutSearchModes = QtGui.QVBoxLayout()
        self.verticalLayoutSearchModes.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayoutSearchModes.setContentsMargins(10, 0, 10, 10)
        self.verticalLayoutSearchModes.setObjectName(_fromUtf8("verticalLayoutSearchModes"))
        self.labelModes = QtGui.QLabel(self.boxSearchSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelModes.sizePolicy().hasHeightForWidth())
        self.labelModes.setSizePolicy(sizePolicy)
        self.labelModes.setMinimumSize(QtCore.QSize(146, 20))
        self.labelModes.setMaximumSize(QtCore.QSize(200, 20))
        self.labelModes.setObjectName(_fromUtf8("labelModes"))
        self.verticalLayoutSearchModes.addWidget(self.labelModes)
        self.verticalLayoutModes = QtGui.QVBoxLayout()
        self.verticalLayoutModes.setContentsMargins(10, 0, 10, 0)
        self.verticalLayoutModes.setObjectName(_fromUtf8("verticalLayoutModes"))
        self.checkBoxEmail = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxEmail.setObjectName(_fromUtf8("checkBoxEmail"))
        self.verticalLayoutModes.addWidget(self.checkBoxEmail)
        self.checkBoxPhone = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxPhone.setObjectName(_fromUtf8("checkBoxPhone"))
        self.verticalLayoutModes.addWidget(self.checkBoxPhone)
        self.checkBoxAddress = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxAddress.setObjectName(_fromUtf8("checkBoxAddress"))
        self.verticalLayoutModes.addWidget(self.checkBoxAddress)
        self.checkBoxManager = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxManager.setObjectName(_fromUtf8("checkBoxManager"))
        self.verticalLayoutModes.addWidget(self.checkBoxManager)
        self.verticalLayoutSearchModes.addLayout(self.verticalLayoutModes)
        self.gridLayoutWidgetSettings.addLayout(self.verticalLayoutSearchModes, 0, 0, 1, 1)
        self.verticalLayoutSearchEngines = QtGui.QVBoxLayout()
        self.verticalLayoutSearchEngines.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayoutSearchEngines.setContentsMargins(10, 0, 10, 10)
        self.verticalLayoutSearchEngines.setObjectName(_fromUtf8("verticalLayoutSearchEngines"))
        self.labelSearchEngines = QtGui.QLabel(self.boxSearchSettings)
        self.labelSearchEngines.setMinimumSize(QtCore.QSize(0, 20))
        self.labelSearchEngines.setMaximumSize(QtCore.QSize(150, 20))
        self.labelSearchEngines.setObjectName(_fromUtf8("labelSearchEngines"))
        self.verticalLayoutSearchEngines.addWidget(self.labelSearchEngines)
        self.verticalLayouEngines = QtGui.QVBoxLayout()
        self.verticalLayouEngines.setContentsMargins(10, 0, 10, 20)
        self.verticalLayouEngines.setObjectName(_fromUtf8("verticalLayouEngines"))
        self.checkBoxGoogle = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxGoogle.setObjectName(_fromUtf8("checkBoxGoogle"))
        self.verticalLayouEngines.addWidget(self.checkBoxGoogle)
        self.checkBoxAsk = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxAsk.setObjectName(_fromUtf8("checkBoxAsk"))
        self.verticalLayouEngines.addWidget(self.checkBoxAsk)
        self.checkBoxBing = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxBing.setObjectName(_fromUtf8("checkBoxBing"))
        self.verticalLayouEngines.addWidget(self.checkBoxBing)
        self.checkBoxMail = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxMail.setObjectName(_fromUtf8("checkBoxMail"))
        self.verticalLayouEngines.addWidget(self.checkBoxMail)
        self.checkBoxRambler = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxRambler.setObjectName(_fromUtf8("checkBoxRambler"))
        self.verticalLayouEngines.addWidget(self.checkBoxRambler)
        self.checkBoxYahoo = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxYahoo.setObjectName(_fromUtf8("checkBoxYahoo"))
        self.verticalLayouEngines.addWidget(self.checkBoxYahoo)
        self.checkBoxYandex = QtGui.QCheckBox(self.boxSearchSettings)
        self.checkBoxYandex.setObjectName(_fromUtf8("checkBoxYandex"))
        self.verticalLayouEngines.addWidget(self.checkBoxYandex)
        self.verticalLayoutSearchEngines.addLayout(self.verticalLayouEngines)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayoutSearchEngines.addItem(spacerItem)
        self.gridLayoutWidgetSettings.addLayout(self.verticalLayoutSearchEngines, 0, 1, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.boxSearchSettings)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutSearchLevel = QtGui.QGridLayout(self.groupBox)
        self.gridLayoutSearchLevel.setMargin(0)
        self.gridLayoutSearchLevel.setObjectName(_fromUtf8("gridLayoutSearchLevel"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(10, 5, 10, 5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelSearchLevel = QtGui.QLabel(self.groupBox)
        self.labelSearchLevel.setText(_fromUtf8("Глубина\n"
"поиска:"))
        self.labelSearchLevel.setObjectName(_fromUtf8("labelSearchLevel"))
        self.gridLayout.addWidget(self.labelSearchLevel, 0, 0, 1, 1)
        self.lcdNumberSearchLevel = QtGui.QLCDNumber(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberSearchLevel.sizePolicy().hasHeightForWidth())
        self.lcdNumberSearchLevel.setSizePolicy(sizePolicy)
        self.lcdNumberSearchLevel.setMinimumSize(QtCore.QSize(46, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Sans Serif"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.lcdNumberSearchLevel.setFont(font)
        self.lcdNumberSearchLevel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumberSearchLevel.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lcdNumberSearchLevel.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumberSearchLevel.setFrameShadow(QtGui.QFrame.Raised)
        self.lcdNumberSearchLevel.setLineWidth(1)
        self.lcdNumberSearchLevel.setMidLineWidth(0)
        self.lcdNumberSearchLevel.setDigitCount(3)
        self.lcdNumberSearchLevel.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberSearchLevel.setProperty("value", 250.0)
        self.lcdNumberSearchLevel.setProperty("intValue", 250)
        self.lcdNumberSearchLevel.setObjectName(_fromUtf8("lcdNumberSearchLevel"))
        self.gridLayout.addWidget(self.lcdNumberSearchLevel, 1, 0, 1, 1)
        self.dialSearchLevel = QtGui.QDial(self.groupBox)
        self.dialSearchLevel.setMaximum(500)
        self.dialSearchLevel.setSingleStep(10)
        self.dialSearchLevel.setPageStep(100)
        self.dialSearchLevel.setProperty("value", 250)
        self.dialSearchLevel.setTracking(False)
        self.dialSearchLevel.setObjectName(_fromUtf8("dialSearchLevel"))
        self.gridLayout.addWidget(self.dialSearchLevel, 0, 1, 2, 1)
        self.gridLayoutSearchLevel.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayoutWidgetSettings.addWidget(self.groupBox, 1, 0, 1, 1)
        self.verticalLayoutOptions = QtGui.QVBoxLayout()
        self.verticalLayoutOptions.setContentsMargins(10, -1, -1, -1)
        self.verticalLayoutOptions.setObjectName(_fromUtf8("verticalLayoutOptions"))
        self.labelSearchOptions = QtGui.QLabel(self.boxSearchSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSearchOptions.sizePolicy().hasHeightForWidth())
        self.labelSearchOptions.setSizePolicy(sizePolicy)
        self.labelSearchOptions.setMinimumSize(QtCore.QSize(146, 20))
        self.labelSearchOptions.setMaximumSize(QtCore.QSize(200, 20))
        self.labelSearchOptions.setObjectName(_fromUtf8("labelSearchOptions"))
        self.verticalLayoutOptions.addWidget(self.labelSearchOptions)
        self.horizontalLayouteTopMode = QtGui.QHBoxLayout()
        self.horizontalLayouteTopMode.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayouteTopMode.setObjectName(_fromUtf8("horizontalLayouteTopMode"))
        self.checkBoxTop = QtGui.QCheckBox(self.boxSearchSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxTop.sizePolicy().hasHeightForWidth())
        self.checkBoxTop.setSizePolicy(sizePolicy)
        self.checkBoxTop.setMinimumSize(QtCore.QSize(260, 0))
        self.checkBoxTop.setObjectName(_fromUtf8("checkBoxTop"))
        self.horizontalLayouteTopMode.addWidget(self.checkBoxTop)
        self.verticalLayoutOptions.addLayout(self.horizontalLayouteTopMode)
        self.gridLayoutWidgetSettings.addLayout(self.verticalLayoutOptions, 2, 0, 1, 2)
        self.verticalLayoutRating = QtGui.QVBoxLayout()
        self.verticalLayoutRating.setContentsMargins(10, -1, -1, -1)
        self.verticalLayoutRating.setObjectName(_fromUtf8("verticalLayoutRating"))
        self.labelSearchRating = QtGui.QLabel(self.boxSearchSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSearchRating.sizePolicy().hasHeightForWidth())
        self.labelSearchRating.setSizePolicy(sizePolicy)
        self.labelSearchRating.setMinimumSize(QtCore.QSize(146, 20))
        self.labelSearchRating.setMaximumSize(QtCore.QSize(200, 20))
        self.labelSearchRating.setObjectName(_fromUtf8("labelSearchRating"))
        self.verticalLayoutRating.addWidget(self.labelSearchRating)
        self.horizontalLayouteRating = QtGui.QHBoxLayout()
        self.horizontalLayouteRating.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayouteRating.setContentsMargins(8, -1, 12, -1)
        self.horizontalLayouteRating.setObjectName(_fromUtf8("horizontalLayouteRating"))
        self.spinBoxThreshold = QtGui.QSpinBox(self.boxSearchSettings)
        self.spinBoxThreshold.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxThreshold.setFont(font)
        self.spinBoxThreshold.setMaximum(1000)
        self.spinBoxThreshold.setProperty("value", 100)
        self.spinBoxThreshold.setObjectName(_fromUtf8("spinBoxThreshold"))
        self.horizontalLayouteRating.addWidget(self.spinBoxThreshold)
        self.sliderRating = QtGui.QSlider(self.boxSearchSettings)
        self.sliderRating.setMinimum(0)
        self.sliderRating.setMaximum(1000)
        self.sliderRating.setSingleStep(10)
        self.sliderRating.setPageStep(100)
        self.sliderRating.setSliderPosition(100)
        self.sliderRating.setOrientation(QtCore.Qt.Horizontal)
        self.sliderRating.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderRating.setTickInterval(100)
        self.sliderRating.setObjectName(_fromUtf8("sliderRating"))
        self.horizontalLayouteRating.addWidget(self.sliderRating)
        self.verticalLayoutRating.addLayout(self.horizontalLayouteRating)
        self.gridLayoutWidgetSettings.addLayout(self.verticalLayoutRating, 3, 0, 1, 2)
        self.line = QtGui.QFrame(self.boxSearchSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayoutWidgetSettings.addWidget(self.line, 4, 0, 1, 2)
        self.horizontalLayoutLoadingDisable = QtGui.QHBoxLayout()
        self.horizontalLayoutLoadingDisable.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayoutLoadingDisable.setObjectName(_fromUtf8("horizontalLayoutLoadingDisable"))
        self.checkBoxLoadingDisable = QtGui.QCheckBox(self.boxSearchSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxLoadingDisable.sizePolicy().hasHeightForWidth())
        self.checkBoxLoadingDisable.setSizePolicy(sizePolicy)
        self.checkBoxLoadingDisable.setMinimumSize(QtCore.QSize(250, 0))
        self.checkBoxLoadingDisable.setObjectName(_fromUtf8("checkBoxLoadingDisable"))
        self.horizontalLayoutLoadingDisable.addWidget(self.checkBoxLoadingDisable)
        self.gridLayoutWidgetSettings.addLayout(self.horizontalLayoutLoadingDisable, 5, 0, 1, 2)
        self.line.raise_()
        self.groupBox.raise_()
        self.labelSearchOptions.raise_()
        self.labelSearchRating.raise_()
        self.gridLayoutWidget.addWidget(self.boxSearchSettings, 0, 0, 1, 1)
        self.labelSearchLevel.setBuddy(self.dialSearchLevel)

        self.retranslateUi(DialogSettings)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogSettings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogSettings.reject)
        QtCore.QObject.connect(self.dialSearchLevel, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumberSearchLevel.display)
        QtCore.QObject.connect(self.dialSearchLevel, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.lcdNumberSearchLevel.display)
        QtCore.QObject.connect(self.sliderRating, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinBoxThreshold.setValue)
        QtCore.QObject.connect(self.sliderRating, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBoxThreshold.setValue)
        QtCore.QObject.connect(self.spinBoxThreshold, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.sliderRating.setValue)
        QtCore.QMetaObject.connectSlotsByName(DialogSettings)

    def retranslateUi(self, DialogSettings):
        DialogSettings.setWindowTitle(_translate("DialogSettings", "Настройки", None))
        self.boxSearchSettings.setTitle(_translate("DialogSettings", "Настройки поиска:", None))
        self.labelModes.setText(_translate("DialogSettings", "Контекст поиска (режимы):", None))
        self.checkBoxEmail.setText(_translate("DialogSettings", "Emails", None))
        self.checkBoxPhone.setText(_translate("DialogSettings", "Телефоны", None))
        self.checkBoxAddress.setText(_translate("DialogSettings", "Адреса", None))
        self.checkBoxManager.setText(_translate("DialogSettings", "ФИО", None))
        self.labelSearchEngines.setText(_translate("DialogSettings", "Поисковые сервисы:", None))
        self.checkBoxGoogle.setText(_translate("DialogSettings", "Google", None))
        self.checkBoxAsk.setText(_translate("DialogSettings", "Ask", None))
        self.checkBoxBing.setText(_translate("DialogSettings", "Bing", None))
        self.checkBoxMail.setText(_translate("DialogSettings", "Mail.ru", None))
        self.checkBoxRambler.setText(_translate("DialogSettings", "Rambler", None))
        self.checkBoxYahoo.setText(_translate("DialogSettings", "Yahoo", None))
        self.checkBoxYandex.setText(_translate("DialogSettings", "Yandex", None))
        self.labelSearchOptions.setText(_translate("DialogSettings", "Опции поиска:", None))
        self.checkBoxTop.setText(_translate("DialogSettings", "TOP (только сайты компаний)", None))
        self.labelSearchRating.setText(_translate("DialogSettings", "Минимальный рейтинг:", None))
        self.checkBoxLoadingDisable.setText(_translate("DialogSettings", "Отключить загрузку картотеки", None))

