# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(942, 635)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(942, 635))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(1900, 1600))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutCentral = QtGui.QGridLayout(self.centralwidget)
        self.gridLayoutCentral.setContentsMargins(12, -1, -1, -1)
        self.gridLayoutCentral.setObjectName(_fromUtf8("gridLayoutCentral"))
        self.gridLayoutWidget = QtGui.QGridLayout()
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayoutHeader = QtGui.QGridLayout()
        self.gridLayoutHeader.setContentsMargins(-1, -1, 20, 6)
        self.gridLayoutHeader.setObjectName(_fromUtf8("gridLayoutHeader"))
        self.labelHeader = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHeader.sizePolicy().hasHeightForWidth())
        self.labelHeader.setSizePolicy(sizePolicy)
        self.labelHeader.setMinimumSize(QtCore.QSize(400, 50))
        self.labelHeader.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelHeader.setFont(font)
        self.labelHeader.setIndent(-1)
        self.labelHeader.setObjectName(_fromUtf8("labelHeader"))
        self.gridLayoutHeader.addWidget(self.labelHeader, 0, 0, 1, 2)
        self.horizontalLayoutSettings = QtGui.QHBoxLayout()
        self.horizontalLayoutSettings.setObjectName(_fromUtf8("horizontalLayoutSettings"))
        self.horizontalLayoutFromDate = QtGui.QHBoxLayout()
        self.horizontalLayoutFromDate.setContentsMargins(0, -1, 10, 0)
        self.horizontalLayoutFromDate.setSpacing(6)
        self.horizontalLayoutFromDate.setObjectName(_fromUtf8("horizontalLayoutFromDate"))
        self.labelDateFrom = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateFrom.sizePolicy().hasHeightForWidth())
        self.labelDateFrom.setSizePolicy(sizePolicy)
        self.labelDateFrom.setMinimumSize(QtCore.QSize(60, 0))
        self.labelDateFrom.setMaximumSize(QtCore.QSize(60, 20))
        self.labelDateFrom.setObjectName(_fromUtf8("labelDateFrom"))
        self.horizontalLayoutFromDate.addWidget(self.labelDateFrom)
        self.boxDateFrom = QtGui.QDateEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxDateFrom.sizePolicy().hasHeightForWidth())
        self.boxDateFrom.setSizePolicy(sizePolicy)
        self.boxDateFrom.setMinimumSize(QtCore.QSize(0, 0))
        self.boxDateFrom.setMaximumSize(QtCore.QSize(120, 24))
        self.boxDateFrom.setBaseSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boxDateFrom.setFont(font)
        self.boxDateFrom.setAlignment(QtCore.Qt.AlignCenter)
        self.boxDateFrom.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 10, 1), QtCore.QTime(0, 0, 0)))
        self.boxDateFrom.setDate(QtCore.QDate(2015, 10, 1))
        self.boxDateFrom.setCalendarPopup(True)
        self.boxDateFrom.setObjectName(_fromUtf8("boxDateFrom"))
        self.horizontalLayoutFromDate.addWidget(self.boxDateFrom)
        self.horizontalLayoutSettings.addLayout(self.horizontalLayoutFromDate)
        self.buttonSettings = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSettings.sizePolicy().hasHeightForWidth())
        self.buttonSettings.setSizePolicy(sizePolicy)
        self.buttonSettings.setMinimumSize(QtCore.QSize(140, 26))
        self.buttonSettings.setMaximumSize(QtCore.QSize(140, 26))
        self.buttonSettings.setBaseSize(QtCore.QSize(0, 0))
        self.buttonSettings.setObjectName(_fromUtf8("buttonSettings"))
        self.horizontalLayoutSettings.addWidget(self.buttonSettings)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutSettings.addItem(spacerItem)
        self.gridLayoutHeader.addLayout(self.horizontalLayoutSettings, 1, 0, 1, 1)
        self.gridLayoutProgress = QtGui.QGridLayout()
        self.gridLayoutProgress.setContentsMargins(-1, -1, 222, -1)
        self.gridLayoutProgress.setObjectName(_fromUtf8("gridLayoutProgress"))
        self.progressBarTop = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarTop.sizePolicy().hasHeightForWidth())
        self.progressBarTop.setSizePolicy(sizePolicy)
        self.progressBarTop.setMinimumSize(QtCore.QSize(0, 16))
        self.progressBarTop.setMaximumSize(QtCore.QSize(1200, 16))
        self.progressBarTop.setProperty("value", 24)
        self.progressBarTop.setObjectName(_fromUtf8("progressBarTop"))
        self.gridLayoutProgress.addWidget(self.progressBarTop, 1, 0, 1, 1)
        self.labelTopProgress = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTopProgress.sizePolicy().hasHeightForWidth())
        self.labelTopProgress.setSizePolicy(sizePolicy)
        self.labelTopProgress.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelTopProgress.setObjectName(_fromUtf8("labelTopProgress"))
        self.gridLayoutProgress.addWidget(self.labelTopProgress, 0, 0, 1, 1)
        self.progressBarBottom = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarBottom.sizePolicy().hasHeightForWidth())
        self.progressBarBottom.setSizePolicy(sizePolicy)
        self.progressBarBottom.setMinimumSize(QtCore.QSize(0, 16))
        self.progressBarBottom.setMaximumSize(QtCore.QSize(1200, 16))
        self.progressBarBottom.setProperty("value", 24)
        self.progressBarBottom.setObjectName(_fromUtf8("progressBarBottom"))
        self.gridLayoutProgress.addWidget(self.progressBarBottom, 3, 0, 1, 1)
        self.labelBottomProgress = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBottomProgress.sizePolicy().hasHeightForWidth())
        self.labelBottomProgress.setSizePolicy(sizePolicy)
        self.labelBottomProgress.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelBottomProgress.setObjectName(_fromUtf8("labelBottomProgress"))
        self.gridLayoutProgress.addWidget(self.labelBottomProgress, 2, 0, 1, 1)
        self.gridLayoutHeader.addLayout(self.gridLayoutProgress, 2, 0, 1, 1)
        self.gridLayoutWidget.addLayout(self.gridLayoutHeader, 0, 0, 1, 1)
        self.gridLayoutTopPanel = QtGui.QGridLayout()
        self.gridLayoutTopPanel.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayoutTopPanel.setContentsMargins(-1, 0, 4, -1)
        self.gridLayoutTopPanel.setObjectName(_fromUtf8("gridLayoutTopPanel"))
        self.horizontalLayoutCounts = QtGui.QHBoxLayout()
        self.horizontalLayoutCounts.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayoutCounts.setContentsMargins(-1, 12, -1, 6)
        self.horizontalLayoutCounts.setObjectName(_fromUtf8("horizontalLayoutCounts"))
        self.countTotal = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countTotal.sizePolicy().hasHeightForWidth())
        self.countTotal.setSizePolicy(sizePolicy)
        self.countTotal.setMinimumSize(QtCore.QSize(62, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(16)
        self.countTotal.setFont(font)
        self.countTotal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.countTotal.setFrameShape(QtGui.QFrame.StyledPanel)
        self.countTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countTotal.setObjectName(_fromUtf8("countTotal"))
        self.horizontalLayoutCounts.addWidget(self.countTotal)
        self.countFound = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countFound.sizePolicy().hasHeightForWidth())
        self.countFound.setSizePolicy(sizePolicy)
        self.countFound.setMinimumSize(QtCore.QSize(53, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(16)
        self.countFound.setFont(font)
        self.countFound.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.countFound.setFrameShape(QtGui.QFrame.StyledPanel)
        self.countFound.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countFound.setObjectName(_fromUtf8("countFound"))
        self.horizontalLayoutCounts.addWidget(self.countFound)
        self.countReady = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countReady.sizePolicy().hasHeightForWidth())
        self.countReady.setSizePolicy(sizePolicy)
        self.countReady.setMinimumSize(QtCore.QSize(53, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(16)
        self.countReady.setFont(font)
        self.countReady.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.countReady.setFrameShape(QtGui.QFrame.StyledPanel)
        self.countReady.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countReady.setObjectName(_fromUtf8("countReady"))
        self.horizontalLayoutCounts.addWidget(self.countReady)
        self.countSent = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countSent.sizePolicy().hasHeightForWidth())
        self.countSent.setSizePolicy(sizePolicy)
        self.countSent.setMinimumSize(QtCore.QSize(53, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(16)
        self.countSent.setFont(font)
        self.countSent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.countSent.setFrameShape(QtGui.QFrame.StyledPanel)
        self.countSent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countSent.setObjectName(_fromUtf8("countSent"))
        self.horizontalLayoutCounts.addWidget(self.countSent)
        self.gridLayoutTopPanel.addLayout(self.horizontalLayoutCounts, 0, 0, 1, 1)
        self.horizontalLayoutClock = QtGui.QHBoxLayout()
        self.horizontalLayoutClock.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayoutClock.setContentsMargins(-1, 15, -1, 15)
        self.horizontalLayoutClock.setObjectName(_fromUtf8("horizontalLayoutClock"))
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutClock.addItem(spacerItem1)
        self.lcdClock = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdClock.sizePolicy().hasHeightForWidth())
        self.lcdClock.setSizePolicy(sizePolicy)
        self.lcdClock.setMinimumSize(QtCore.QSize(120, 40))
        self.lcdClock.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Sans Serif"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lcdClock.setFont(font)
        self.lcdClock.setNumDigits(8)
        self.lcdClock.setObjectName(_fromUtf8("lcdClock"))
        self.horizontalLayoutClock.addWidget(self.lcdClock)
        spacerItem2 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutClock.addItem(spacerItem2)
        self.gridLayoutTopPanel.addLayout(self.horizontalLayoutClock, 1, 0, 1, 1)
        self.horizontalLayoutButtons = QtGui.QHBoxLayout()
        self.horizontalLayoutButtons.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayoutButtons.setContentsMargins(10, 0, 10, 20)
        self.horizontalLayoutButtons.setObjectName(_fromUtf8("horizontalLayoutButtons"))
        self.buttonStart = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStart.sizePolicy().hasHeightForWidth())
        self.buttonStart.setSizePolicy(sizePolicy)
        self.buttonStart.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonStart.setFont(font)
        self.buttonStart.setObjectName(_fromUtf8("buttonStart"))
        self.horizontalLayoutButtons.addWidget(self.buttonStart)
        self.buttonStop = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStop.sizePolicy().hasHeightForWidth())
        self.buttonStop.setSizePolicy(sizePolicy)
        self.buttonStop.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonStop.setFont(font)
        self.buttonStop.setObjectName(_fromUtf8("buttonStop"))
        self.horizontalLayoutButtons.addWidget(self.buttonStop)
        self.buttonExit = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonExit.sizePolicy().hasHeightForWidth())
        self.buttonExit.setSizePolicy(sizePolicy)
        self.buttonExit.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonExit.setFont(font)
        self.buttonExit.setObjectName(_fromUtf8("buttonExit"))
        self.horizontalLayoutButtons.addWidget(self.buttonExit)
        self.gridLayoutTopPanel.addLayout(self.horizontalLayoutButtons, 2, 0, 1, 1)
        self.gridLayoutWidget.addLayout(self.gridLayoutTopPanel, 0, 1, 1, 1)
        self.gridLayoutDataPanel = QtGui.QGridLayout()
        self.gridLayoutDataPanel.setObjectName(_fromUtf8("gridLayoutDataPanel"))
        self.gridLayoutData = QtGui.QGridLayout()
        self.gridLayoutData.setObjectName(_fromUtf8("gridLayoutData"))
        self.boxPhones = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxPhones.sizePolicy().hasHeightForWidth())
        self.boxPhones.setSizePolicy(sizePolicy)
        self.boxPhones.setMinimumSize(QtCore.QSize(241, 98))
        self.boxPhones.setMaximumSize(QtCore.QSize(256, 120))
        self.boxPhones.setObjectName(_fromUtf8("boxPhones"))
        self.gridLayoutPhones = QtGui.QGridLayout(self.boxPhones)
        self.gridLayoutPhones.setObjectName(_fromUtf8("gridLayoutPhones"))
        self.viewPhones = QtGui.QListWidget(self.boxPhones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewPhones.sizePolicy().hasHeightForWidth())
        self.viewPhones.setSizePolicy(sizePolicy)
        self.viewPhones.setMinimumSize(QtCore.QSize(0, 0))
        self.viewPhones.setMaximumSize(QtCore.QSize(240, 48))
        self.viewPhones.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.viewPhones.setTabKeyNavigation(True)
        self.viewPhones.setObjectName(_fromUtf8("viewPhones"))
        self.gridLayoutPhones.addWidget(self.viewPhones, 0, 0, 1, 2)
        self.hCommandPanelPhones = QtGui.QHBoxLayout()
        self.hCommandPanelPhones.setSpacing(2)
        self.hCommandPanelPhones.setObjectName(_fromUtf8("hCommandPanelPhones"))
        self.buttonNewPhone = QtGui.QToolButton(self.boxPhones)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/new_16x16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonNewPhone.setIcon(icon)
        self.buttonNewPhone.setIconSize(QtCore.QSize(16, 16))
        self.buttonNewPhone.setObjectName(_fromUtf8("buttonNewPhone"))
        self.hCommandPanelPhones.addWidget(self.buttonNewPhone)
        self.buttonEditPhone = QtGui.QToolButton(self.boxPhones)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/edit_16x16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonEditPhone.setIcon(icon1)
        self.buttonEditPhone.setIconSize(QtCore.QSize(16, 16))
        self.buttonEditPhone.setObjectName(_fromUtf8("buttonEditPhone"))
        self.hCommandPanelPhones.addWidget(self.buttonEditPhone)
        self.buttonRemovePhone = QtGui.QToolButton(self.boxPhones)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/cancel_16x16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRemovePhone.setIcon(icon2)
        self.buttonRemovePhone.setIconSize(QtCore.QSize(16, 16))
        self.buttonRemovePhone.setObjectName(_fromUtf8("buttonRemovePhone"))
        self.hCommandPanelPhones.addWidget(self.buttonRemovePhone)
        self.gridLayoutPhones.addLayout(self.hCommandPanelPhones, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(152, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutPhones.addItem(spacerItem3, 1, 1, 1, 1)
        self.gridLayoutData.addWidget(self.boxPhones, 1, 0, 1, 1)
        self.verticalLayoutCommands = QtGui.QVBoxLayout()
        self.verticalLayoutCommands.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayoutCommands.setContentsMargins(40, 10, 40, 10)
        self.verticalLayoutCommands.setObjectName(_fromUtf8("verticalLayoutCommands"))
        self.buttonOpenOutput = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOpenOutput.sizePolicy().hasHeightForWidth())
        self.buttonOpenOutput.setSizePolicy(sizePolicy)
        self.buttonOpenOutput.setMinimumSize(QtCore.QSize(180, 26))
        self.buttonOpenOutput.setMaximumSize(QtCore.QSize(0, 26))
        self.buttonOpenOutput.setBaseSize(QtCore.QSize(0, 0))
        self.buttonOpenOutput.setObjectName(_fromUtf8("buttonOpenOutput"))
        self.verticalLayoutCommands.addWidget(self.buttonOpenOutput)
        self.buttonOpenDoc = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOpenDoc.sizePolicy().hasHeightForWidth())
        self.buttonOpenDoc.setSizePolicy(sizePolicy)
        self.buttonOpenDoc.setMinimumSize(QtCore.QSize(180, 26))
        self.buttonOpenDoc.setMaximumSize(QtCore.QSize(0, 26))
        self.buttonOpenDoc.setBaseSize(QtCore.QSize(0, 0))
        self.buttonOpenDoc.setObjectName(_fromUtf8("buttonOpenDoc"))
        self.verticalLayoutCommands.addWidget(self.buttonOpenDoc)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayoutCommands.addItem(spacerItem4)
        self.buttonSendMail = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSendMail.sizePolicy().hasHeightForWidth())
        self.buttonSendMail.setSizePolicy(sizePolicy)
        self.buttonSendMail.setMinimumSize(QtCore.QSize(180, 30))
        self.buttonSendMail.setMaximumSize(QtCore.QSize(0, 26))
        self.buttonSendMail.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonSendMail.setFont(font)
        self.buttonSendMail.setDefault(False)
        self.buttonSendMail.setObjectName(_fromUtf8("buttonSendMail"))
        self.verticalLayoutCommands.addWidget(self.buttonSendMail)
        self.gridLayoutData.addLayout(self.verticalLayoutCommands, 2, 0, 1, 1)
        self.boxEmails = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxEmails.sizePolicy().hasHeightForWidth())
        self.boxEmails.setSizePolicy(sizePolicy)
        self.boxEmails.setMinimumSize(QtCore.QSize(241, 98))
        self.boxEmails.setMaximumSize(QtCore.QSize(256, 800))
        self.boxEmails.setObjectName(_fromUtf8("boxEmails"))
        self.gridLayoutEmails = QtGui.QGridLayout(self.boxEmails)
        self.gridLayoutEmails.setObjectName(_fromUtf8("gridLayoutEmails"))
        self.viewEmails = QtGui.QListWidget(self.boxEmails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewEmails.sizePolicy().hasHeightForWidth())
        self.viewEmails.setSizePolicy(sizePolicy)
        self.viewEmails.setMinimumSize(QtCore.QSize(0, 0))
        self.viewEmails.setMaximumSize(QtCore.QSize(240, 680))
        self.viewEmails.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.viewEmails.setTabKeyNavigation(True)
        self.viewEmails.setAlternatingRowColors(False)
        self.viewEmails.setObjectName(_fromUtf8("viewEmails"))
        self.gridLayoutEmails.addWidget(self.viewEmails, 0, 0, 1, 2)
        self.hCommandPanelEmails = QtGui.QHBoxLayout()
        self.hCommandPanelEmails.setSpacing(2)
        self.hCommandPanelEmails.setObjectName(_fromUtf8("hCommandPanelEmails"))
        self.buttonNewEmail = QtGui.QToolButton(self.boxEmails)
        self.buttonNewEmail.setIcon(icon)
        self.buttonNewEmail.setIconSize(QtCore.QSize(16, 16))
        self.buttonNewEmail.setObjectName(_fromUtf8("buttonNewEmail"))
        self.hCommandPanelEmails.addWidget(self.buttonNewEmail)
        self.buttonEditEmail = QtGui.QToolButton(self.boxEmails)
        self.buttonEditEmail.setIcon(icon1)
        self.buttonEditEmail.setIconSize(QtCore.QSize(16, 16))
        self.buttonEditEmail.setObjectName(_fromUtf8("buttonEditEmail"))
        self.hCommandPanelEmails.addWidget(self.buttonEditEmail)
        self.buttonRemoveEmail = QtGui.QToolButton(self.boxEmails)
        self.buttonRemoveEmail.setIcon(icon2)
        self.buttonRemoveEmail.setIconSize(QtCore.QSize(16, 16))
        self.buttonRemoveEmail.setObjectName(_fromUtf8("buttonRemoveEmail"))
        self.hCommandPanelEmails.addWidget(self.buttonRemoveEmail)
        self.gridLayoutEmails.addLayout(self.hCommandPanelEmails, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(152, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutEmails.addItem(spacerItem5, 1, 1, 1, 1)
        self.gridLayoutData.addWidget(self.boxEmails, 0, 0, 1, 1)
        self.gridLayoutDataPanel.addLayout(self.gridLayoutData, 0, 2, 3, 1)
        self.horizontalDBLayout = QtGui.QHBoxLayout()
        self.horizontalDBLayout.setObjectName(_fromUtf8("horizontalDBLayout"))
        self.pageCommandPanel = QtGui.QHBoxLayout()
        self.pageCommandPanel.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.pageCommandPanel.setContentsMargins(-1, -1, 0, -1)
        self.pageCommandPanel.setSpacing(2)
        self.pageCommandPanel.setObjectName(_fromUtf8("pageCommandPanel"))
        self.buttonFirst = QtGui.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/first.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFirst.setIcon(icon3)
        self.buttonFirst.setIconSize(QtCore.QSize(16, 16))
        self.buttonFirst.setObjectName(_fromUtf8("buttonFirst"))
        self.pageCommandPanel.addWidget(self.buttonFirst)
        self.buttonPrevious = QtGui.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/prev.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPrevious.setIcon(icon4)
        self.buttonPrevious.setIconSize(QtCore.QSize(16, 16))
        self.buttonPrevious.setObjectName(_fromUtf8("buttonPrevious"))
        self.pageCommandPanel.addWidget(self.buttonPrevious)
        self.buttonNext = QtGui.QToolButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("images/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonNext.setIcon(icon5)
        self.buttonNext.setIconSize(QtCore.QSize(16, 16))
        self.buttonNext.setObjectName(_fromUtf8("buttonNext"))
        self.pageCommandPanel.addWidget(self.buttonNext)
        self.buttonLast = QtGui.QToolButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("images/last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLast.setIcon(icon6)
        self.buttonLast.setIconSize(QtCore.QSize(16, 16))
        self.buttonLast.setObjectName(_fromUtf8("buttonLast"))
        self.pageCommandPanel.addWidget(self.buttonLast)
        self.horizontalDBLayout.addLayout(self.pageCommandPanel)
        self.pageSize = QtGui.QHBoxLayout()
        self.pageSize.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.pageSize.setObjectName(_fromUtf8("pageSize"))
        self.boxPageSize = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxPageSize.sizePolicy().hasHeightForWidth())
        self.boxPageSize.setSizePolicy(sizePolicy)
        self.boxPageSize.setMinimumSize(QtCore.QSize(50, 25))
        self.boxPageSize.setMaximumSize(QtCore.QSize(50, 16777215))
        self.boxPageSize.setMaxCount(10)
        self.boxPageSize.setObjectName(_fromUtf8("boxPageSize"))
        self.pageSize.addWidget(self.boxPageSize)
        self.horizontalDBLayout.addLayout(self.pageSize)
        self.horizontalFilterLayout = QtGui.QHBoxLayout()
        self.horizontalFilterLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalFilterLayout.setObjectName(_fromUtf8("horizontalFilterLayout"))
        self.labelFilter = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilter.sizePolicy().hasHeightForWidth())
        self.labelFilter.setSizePolicy(sizePolicy)
        self.labelFilter.setMinimumSize(QtCore.QSize(42, 0))
        self.labelFilter.setMaximumSize(QtCore.QSize(42, 24))
        self.labelFilter.setObjectName(_fromUtf8("labelFilter"))
        self.horizontalFilterLayout.addWidget(self.labelFilter)
        self.boxFilterColumn = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxFilterColumn.sizePolicy().hasHeightForWidth())
        self.boxFilterColumn.setSizePolicy(sizePolicy)
        self.boxFilterColumn.setMinimumSize(QtCore.QSize(80, 25))
        self.boxFilterColumn.setMaximumSize(QtCore.QSize(110, 16777215))
        self.boxFilterColumn.setMaxCount(10)
        self.boxFilterColumn.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.boxFilterColumn.setMinimumContentsLength(0)
        self.boxFilterColumn.setObjectName(_fromUtf8("boxFilterColumn"))
        self.horizontalFilterLayout.addWidget(self.boxFilterColumn)
        self.lineFilterText = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineFilterText.sizePolicy().hasHeightForWidth())
        self.lineFilterText.setSizePolicy(sizePolicy)
        self.lineFilterText.setMinimumSize(QtCore.QSize(20, 23))
        self.lineFilterText.setMaximumSize(QtCore.QSize(820, 23))
        self.lineFilterText.setObjectName(_fromUtf8("lineFilterText"))
        self.horizontalFilterLayout.addWidget(self.lineFilterText)
        self.buttonFilterGo = QtGui.QToolButton(self.centralwidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("images/search_16x16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFilterGo.setIcon(icon7)
        self.buttonFilterGo.setIconSize(QtCore.QSize(16, 16))
        self.buttonFilterGo.setObjectName(_fromUtf8("buttonFilterGo"))
        self.horizontalFilterLayout.addWidget(self.buttonFilterGo)
        self.horizontalFilterLayout.setStretch(1, 1)
        self.horizontalDBLayout.addLayout(self.horizontalFilterLayout)
        self.gridLayoutDataPanel.addLayout(self.horizontalDBLayout, 0, 0, 1, 1)
        self.gridLayoutDetailed = QtGui.QGridLayout()
        self.gridLayoutDetailed.setObjectName(_fromUtf8("gridLayoutDetailed"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.hCommandPanel = QtGui.QHBoxLayout()
        self.hCommandPanel.setSpacing(2)
        self.hCommandPanel.setObjectName(_fromUtf8("hCommandPanel"))
        self.buttonRefresh = QtGui.QToolButton(self.centralwidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("images/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRefresh.setIcon(icon8)
        self.buttonRefresh.setIconSize(QtCore.QSize(16, 16))
        self.buttonRefresh.setObjectName(_fromUtf8("buttonRefresh"))
        self.hCommandPanel.addWidget(self.buttonRefresh)
        self.buttonUnselect = QtGui.QToolButton(self.centralwidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("images/unselect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUnselect.setIcon(icon9)
        self.buttonUnselect.setIconSize(QtCore.QSize(16, 16))
        self.buttonUnselect.setObjectName(_fromUtf8("buttonUnselect"))
        self.hCommandPanel.addWidget(self.buttonUnselect)
        self.buttonSave = QtGui.QToolButton(self.centralwidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("images/star_16x16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSave.setIcon(icon10)
        self.buttonSave.setIconSize(QtCore.QSize(16, 16))
        self.buttonSave.setObjectName(_fromUtf8("buttonSave"))
        self.hCommandPanel.addWidget(self.buttonSave)
        self.buttonRemoveCase = QtGui.QToolButton(self.centralwidget)
        self.buttonRemoveCase.setIcon(icon2)
        self.buttonRemoveCase.setIconSize(QtCore.QSize(16, 16))
        self.buttonRemoveCase.setObjectName(_fromUtf8("buttonRemoveCase"))
        self.hCommandPanel.addWidget(self.buttonRemoveCase)
        self.horizontalLayout.addLayout(self.hCommandPanel)
        spacerItem6 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.hStatus = QtGui.QHBoxLayout()
        self.hStatus.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.hStatus.setObjectName(_fromUtf8("hStatus"))
        self.labelStatus = QtGui.QLabel(self.centralwidget)
        self.labelStatus.setMaximumSize(QtCore.QSize(80, 16777215))
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.hStatus.addWidget(self.labelStatus)
        self.boxStatus = QtGui.QComboBox(self.centralwidget)
        self.boxStatus.setMinimumSize(QtCore.QSize(110, 25))
        self.boxStatus.setMaximumSize(QtCore.QSize(180, 16777215))
        self.boxStatus.setMaxCount(10)
        self.boxStatus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.boxStatus.setMinimumContentsLength(0)
        self.boxStatus.setObjectName(_fromUtf8("boxStatus"))
        self.hStatus.addWidget(self.boxStatus)
        self.horizontalLayout.addLayout(self.hStatus)
        self.gridLayoutDetailed.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.groupDetailed = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupDetailed.sizePolicy().hasHeightForWidth())
        self.groupDetailed.setSizePolicy(sizePolicy)
        self.groupDetailed.setMinimumSize(QtCore.QSize(280, 0))
        self.groupDetailed.setObjectName(_fromUtf8("groupDetailed"))
        self.verticalLayoutDetailed = QtGui.QVBoxLayout(self.groupDetailed)
        self.verticalLayoutDetailed.setContentsMargins(9, -1, 9, -1)
        self.verticalLayoutDetailed.setObjectName(_fromUtf8("verticalLayoutDetailed"))
        self.vFromName = QtGui.QVBoxLayout()
        self.vFromName.setObjectName(_fromUtf8("vFromName"))
        self.labelFromName = QtGui.QLabel(self.groupDetailed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFromName.sizePolicy().hasHeightForWidth())
        self.labelFromName.setSizePolicy(sizePolicy)
        self.labelFromName.setMaximumSize(QtCore.QSize(34, 13))
        self.labelFromName.setObjectName(_fromUtf8("labelFromName"))
        self.vFromName.addWidget(self.labelFromName)
        self.textFromName = QtGui.QTextEdit(self.groupDetailed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textFromName.sizePolicy().hasHeightForWidth())
        self.textFromName.setSizePolicy(sizePolicy)
        self.textFromName.setMinimumSize(QtCore.QSize(258, 40))
        self.textFromName.setMaximumSize(QtCore.QSize(260, 100))
        self.textFromName.setObjectName(_fromUtf8("textFromName"))
        self.vFromName.addWidget(self.textFromName)
        self.verticalLayoutDetailed.addLayout(self.vFromName)
        self.vToName = QtGui.QVBoxLayout()
        self.vToName.setObjectName(_fromUtf8("vToName"))
        self.labelToName = QtGui.QLabel(self.groupDetailed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelToName.sizePolicy().hasHeightForWidth())
        self.labelToName.setSizePolicy(sizePolicy)
        self.labelToName.setMinimumSize(QtCore.QSize(100, 13))
        self.labelToName.setMaximumSize(QtCore.QSize(100, 13))
        self.labelToName.setObjectName(_fromUtf8("labelToName"))
        self.vToName.addWidget(self.labelToName)
        self.textToName = QtGui.QTextEdit(self.groupDetailed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textToName.sizePolicy().hasHeightForWidth())
        self.textToName.setSizePolicy(sizePolicy)
        self.textToName.setMinimumSize(QtCore.QSize(258, 40))
        self.textToName.setMaximumSize(QtCore.QSize(260, 100))
        self.textToName.setObjectName(_fromUtf8("textToName"))
        self.vToName.addWidget(self.textToName)
        self.verticalLayoutDetailed.addLayout(self.vToName)
        self.vToAddress = QtGui.QVBoxLayout()
        self.vToAddress.setObjectName(_fromUtf8("vToAddress"))
        self.labelToAddress = QtGui.QLabel(self.groupDetailed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelToAddress.sizePolicy().hasHeightForWidth())
        self.labelToAddress.setSizePolicy(sizePolicy)
        self.labelToAddress.setMinimumSize(QtCore.QSize(92, 13))
        self.labelToAddress.setMaximumSize(QtCore.QSize(92, 13))
        self.labelToAddress.setObjectName(_fromUtf8("labelToAddress"))
        self.vToAddress.addWidget(self.labelToAddress)
        self.textToAddress = QtGui.QTextEdit(self.groupDetailed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textToAddress.sizePolicy().hasHeightForWidth())
        self.textToAddress.setSizePolicy(sizePolicy)
        self.textToAddress.setMinimumSize(QtCore.QSize(258, 40))
        self.textToAddress.setMaximumSize(QtCore.QSize(260, 120))
        self.textToAddress.setObjectName(_fromUtf8("textToAddress"))
        self.vToAddress.addWidget(self.textToAddress)
        self.verticalLayoutDetailed.addLayout(self.vToAddress)
        self.boxFio = QtGui.QGroupBox(self.groupDetailed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxFio.sizePolicy().hasHeightForWidth())
        self.boxFio.setSizePolicy(sizePolicy)
        self.boxFio.setMinimumSize(QtCore.QSize(260, 91))
        self.boxFio.setMaximumSize(QtCore.QSize(260, 200))
        self.boxFio.setObjectName(_fromUtf8("boxFio"))
        self.gridLayout = QtGui.QGridLayout(self.boxFio)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textManager = QtGui.QTextEdit(self.boxFio)
        self.textManager.setMinimumSize(QtCore.QSize(238, 58))
        self.textManager.setMaximumSize(QtCore.QSize(238, 180))
        self.textManager.setObjectName(_fromUtf8("textManager"))
        self.gridLayout.addWidget(self.textManager, 0, 0, 1, 1)
        self.verticalLayoutDetailed.addWidget(self.boxFio)
        self.gridLayoutDetailed.addWidget(self.groupDetailed, 1, 0, 1, 1)
        self.gridLayoutDataPanel.addLayout(self.gridLayoutDetailed, 0, 1, 3, 1)
        self.tableResults = QtGui.QTableWidget(self.centralwidget)
        self.tableResults.setMinimumSize(QtCore.QSize(320, 350))
        self.tableResults.setMaximumSize(QtCore.QSize(1900, 1400))
        self.tableResults.setObjectName(_fromUtf8("tableResults"))
        self.tableResults.setColumnCount(0)
        self.tableResults.setRowCount(0)
        self.gridLayoutDataPanel.addWidget(self.tableResults, 2, 0, 1, 1)
        self.gridLayoutWidget.addLayout(self.gridLayoutDataPanel, 1, 0, 1, 2)
        self.gridLayoutCentral.addLayout(self.gridLayoutWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.labelDateFrom.setBuddy(self.boxDateFrom)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.buttonSettings, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on_buttonSettings_clicked)
        QtCore.QObject.connect(self.buttonOpenOutput, QtCore.SIGNAL(_fromUtf8("released()")), MainWindow.openOutput)
        QtCore.QObject.connect(self.buttonOpenDoc, QtCore.SIGNAL(_fromUtf8("released()")), MainWindow.openDoc)
        QtCore.QObject.connect(self.buttonSendMail, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on_buttonSendMail_clicked)
        QtCore.QObject.connect(self.buttonStart, QtCore.SIGNAL(_fromUtf8("released()")), MainWindow.buttonStartReleased)
        QtCore.QObject.connect(self.buttonStop, QtCore.SIGNAL(_fromUtf8("released()")), MainWindow.buttonStopReleased)
        QtCore.QObject.connect(self.buttonExit, QtCore.SIGNAL(_fromUtf8("released()")), MainWindow.exit)
        QtCore.QObject.connect(self.buttonRefresh, QtCore.SIGNAL(_fromUtf8("released()")), MainWindow.refresh)
        QtCore.QObject.connect(self.buttonUnselect, QtCore.SIGNAL(_fromUtf8("released()")), MainWindow.unselect)
        QtCore.QObject.connect(self.buttonSave, QtCore.SIGNAL(_fromUtf8("released()")), MainWindow.save)
        QtCore.QObject.connect(self.buttonNewEmail, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.newEmail)
        QtCore.QObject.connect(self.buttonEditEmail, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.editEmail)
        QtCore.QObject.connect(self.buttonRemoveEmail, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.removeEmail)
        QtCore.QObject.connect(self.buttonNewPhone, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.newPhone)
        QtCore.QObject.connect(self.buttonEditPhone, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.editPhone)
        QtCore.QObject.connect(self.buttonRemovePhone, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.removePhone)
        QtCore.QObject.connect(self.viewEmails, QtCore.SIGNAL(_fromUtf8("itemChanged(QListWidgetItem*)")), MainWindow.emailChanged)
        QtCore.QObject.connect(self.viewEmails, QtCore.SIGNAL(_fromUtf8("itemClicked(QListWidgetItem*)")), MainWindow.emailClicked)
        QtCore.QObject.connect(self.viewPhones, QtCore.SIGNAL(_fromUtf8("itemChanged(QListWidgetItem*)")), MainWindow.phoneChanged)
        QtCore.QObject.connect(self.viewPhones, QtCore.SIGNAL(_fromUtf8("itemClicked(QListWidgetItem*)")), MainWindow.phoneClicked)
        QtCore.QObject.connect(self.buttonFirst, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.firstPage)
        QtCore.QObject.connect(self.buttonPrevious, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.prevPage)
        QtCore.QObject.connect(self.buttonLast, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.lastPage)
        QtCore.QObject.connect(self.buttonNext, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.nextPage)
        QtCore.QObject.connect(self.buttonFilterGo, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.search)
        QtCore.QObject.connect(self.buttonRemoveCase, QtCore.SIGNAL(_fromUtf8("released()")), MainWindow.removeCase)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Оферта. Главное окно", None))
        self.labelHeader.setText(_translate("MainWindow", "Картотека арбитражных дел. Оферта", None))
        self.labelDateFrom.setText(_translate("MainWindow", "Период с:", None))
        self.buttonSettings.setText(_translate("MainWindow", "Настройки поиска", None))
        self.labelTopProgress.setText(_translate("MainWindow", "Картотека арбитражных дел...", None))
        self.labelBottomProgress.setText(_translate("MainWindow", "Картотека арбитражных дел...", None))
        self.countTotal.setToolTip(_translate("MainWindow", "<html><head/><body><p>Всего в базе данных</p></body></html>", None))
        self.countTotal.setText(_translate("MainWindow", "9999", None))
        self.countFound.setToolTip(_translate("MainWindow", "<html><head/><body><p>Найдено новых записей</p></body></html>", None))
        self.countFound.setText(_translate("MainWindow", "001", None))
        self.countReady.setToolTip(_translate("MainWindow", "<html><head/><body><p>Готово к рассылке</p></body></html>", None))
        self.countReady.setText(_translate("MainWindow", "001", None))
        self.countSent.setToolTip(_translate("MainWindow", "<html><head/><body><p>Разослано</p></body></html>", None))
        self.countSent.setText(_translate("MainWindow", "001", None))
        self.buttonStart.setText(_translate("MainWindow", "Старт", None))
        self.buttonStop.setText(_translate("MainWindow", "Стоп", None))
        self.buttonExit.setText(_translate("MainWindow", "Выход", None))
        self.boxPhones.setTitle(_translate("MainWindow", "Телефоны", None))
        self.buttonNewPhone.setToolTip(_translate("MainWindow", "Добавить", None))
        self.buttonNewPhone.setText(_translate("MainWindow", "...", None))
        self.buttonEditPhone.setToolTip(_translate("MainWindow", "Изменить", None))
        self.buttonEditPhone.setText(_translate("MainWindow", "...", None))
        self.buttonRemovePhone.setToolTip(_translate("MainWindow", "Удалить", None))
        self.buttonRemovePhone.setText(_translate("MainWindow", "...", None))
        self.buttonOpenOutput.setText(_translate("MainWindow", "Открыть файл результатов", None))
        self.buttonOpenDoc.setText(_translate("MainWindow", "Открыть оферту", None))
        self.buttonSendMail.setText(_translate("MainWindow", "Разослать", None))
        self.boxEmails.setTitle(_translate("MainWindow", "Emails", None))
        self.buttonNewEmail.setToolTip(_translate("MainWindow", "Добавить", None))
        self.buttonNewEmail.setText(_translate("MainWindow", "...", None))
        self.buttonEditEmail.setToolTip(_translate("MainWindow", "Изменить", None))
        self.buttonEditEmail.setText(_translate("MainWindow", "...", None))
        self.buttonRemoveEmail.setToolTip(_translate("MainWindow", "Удалить", None))
        self.buttonRemoveEmail.setText(_translate("MainWindow", "...", None))
        self.buttonFirst.setToolTip(_translate("MainWindow", "<html><head/><body><p>Первая страница</p></body></html>", None))
        self.buttonFirst.setText(_translate("MainWindow", "...", None))
        self.buttonPrevious.setToolTip(_translate("MainWindow", "<html><head/><body><p>Предыдущая страница</p></body></html>", None))
        self.buttonPrevious.setText(_translate("MainWindow", "...", None))
        self.buttonNext.setToolTip(_translate("MainWindow", "<html><head/><body><p>Следующая страница</p></body></html>", None))
        self.buttonNext.setText(_translate("MainWindow", "...", None))
        self.buttonLast.setToolTip(_translate("MainWindow", "<html><head/><body><p>Последняя страница</p></body></html>", None))
        self.buttonLast.setText(_translate("MainWindow", "...", None))
        self.boxPageSize.setToolTip(_translate("MainWindow", "<html><head/><body><p>Размер страницы</p></body></html>", None))
        self.labelFilter.setText(_translate("MainWindow", "Фильтр:", None))
        self.buttonFilterGo.setToolTip(_translate("MainWindow", "Найти", None))
        self.buttonFilterGo.setText(_translate("MainWindow", "...", None))
        self.buttonRefresh.setToolTip(_translate("MainWindow", "Обновить", None))
        self.buttonRefresh.setText(_translate("MainWindow", "...", None))
        self.buttonUnselect.setToolTip(_translate("MainWindow", "Снять отмеченные", None))
        self.buttonUnselect.setText(_translate("MainWindow", "...", None))
        self.buttonSave.setToolTip(_translate("MainWindow", "Сохранить", None))
        self.buttonSave.setText(_translate("MainWindow", "...", None))
        self.buttonRemoveCase.setToolTip(_translate("MainWindow", "Удалить дело", None))
        self.buttonRemoveCase.setText(_translate("MainWindow", "...", None))
        self.labelStatus.setText(_translate("MainWindow", "Статус:", None))
        self.groupDetailed.setTitle(_translate("MainWindow", "Расшифровка", None))
        self.labelFromName.setText(_translate("MainWindow", "Истец:", None))
        self.labelToName.setText(_translate("MainWindow", "Ответчик:", None))
        self.labelToAddress.setText(_translate("MainWindow", "Адрес ответчика:", None))
        self.boxFio.setTitle(_translate("MainWindow", "ФИО", None))

